import './globals.css'
import Header from "@/app/component/Header";
import { Mulish } from 'next/font/google';
import Footer from "@/app/component/Footer";


const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>

      <body>
      <Header/>
      {children}
      <Footer/>


      </body>
    </html>
  )
}
